[project]
name = "lab3_satyamohanreddy_ginni"
version = "0.1.0"
description = "Penguins classification lab with XGBoost and FastAPI"
requires-python = ">=3.8"

dependencies = [
    "fastapi",
    "uvicorn",
    "xgboost",
    "seaborn",
    "scikit-learn",
    "joblib",
    "uv"
]
